version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: sneaker-drop-postgres
    environment:
      POSTGRES_DB: sneaker_drop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - sneaker_drop_pgdata:/var/lib/postgresql/data

volumes:
  sneaker_drop_pgdata:
